### ISSUE TITLE
Support Nova 4

### ISSUE THREAD

**Issue by cwray-tech** [outl1ne/nova-sortable#118]
Now that Nova 4 is out, it would be great if we could update this package to support it. Let me know if you would like some help on it and I may be able to dedicate some time to it.

**Comment by scramatte** [comment]
+1

**Comment by daemswibowo** [comment]
+1

**Comment by aromer** [comment]
This is being worked on here:
https://github.com/outl1ne/nova-sortable/pull/117

**Comment by sineld** [comment]
+1

**Comment by sinamiandashti** [comment]
+1 plz

**Comment by Tarpsvo** [comment]
Locked the conversation, as I receive tens of "+1" emails per day. I haven't forgotten my dozen or so packages, but Nova 4 was a ridiculously big update and most of the packages require a lot of stuff to be redone for them to work.
