### ISSUE TITLE
Nova Pagination `load-more` not Loading More rows

### ISSUE THREAD

**Issue by jjjrmy** [outl1ne/nova-sortable#126]
When using then Nova Config: `'pagination' => 'load-more'`, the HasMany component is not adding the new rows received by the response.

![ezgif-1-8be7468d4b](https://user-images.githubusercontent.com/1609800/173249501-45b28ef6-4139-4b0a-a74f-7d59a9ecde71.gif)

Fixing this would somewhat solve the issue of #10 because you won't need to move it across pages.

**Comment by Tarpsvo** [comment]
Heya! Version 3.3.0 addresses this issue. Please try it out. :) Thanks!
