### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stopPropagation')

### ISSUE THREAD

**Issue by jjjrmy** [outl1ne/nova-sortable#127]
When clicking the Up or Down arrow

**Comment by benedict-w** [comment]
I'm getting this too using Nova 4.9.2 and Nova Sortable 3.0.1.

Also the model sort order is not saved although the UI is updated and the message reads "Resources successfully reordered"

**Comment by bendadaniel** [comment]
Same problem :/

**Comment by simon-roland** [comment]
Confirmed, same error. Nova 4.11.0 and Sortable 3.0.1

**Comment by Tarpsvo** [comment]
I think got fixed during one of the updates. Please confirm.
