### ISSUE TITLE
409 when requesting resource detail view

### ISSUE THREAD

**Issue by a-chaudhari** [outl1ne/nova-sortable#128]
I'm upgrading a nova 3 install to nova 4.   I've been running into an issue which I believe comes from this package.  

If I'm browsing the index view of a resource, click on a row, nova receives a 409 error when trying to access the resource detail view and then does a full page refresh.  See screenshot.

If I remove nova-sortable this behavior goes away and the XHR request completes successfully and all is well.  If I reinstall the package the issue comes back.  I removed all other 3rd party nova packages to ensure no weird conflicts.  It didn't help either.

Clicking on the body of the row causes this issue.  However clicking on the "eye" icon completes successfully.

Ordinarily a full page refresh wouldn't be the end of the world.  But for some reason the https connection switches to a http (non-secure) connection when the detail page is hard fetched.  There are other weird state issues as well such apparently not having a currentUser set which causes havoc elsewhere in the webapp.

I'm using nova-sortable 3.0.1, Nova version  4.8.1, and laravel 8.83.16

<img width="1169" alt="Screenshot 2022-06-13 160633" src="https://user-images.githubusercontent.com/8324605/173436995-2e2cb929-d654-4aa1-9b0c-4ca0d6d60155.png">

**Comment by MarkBringNielsen** [comment]
I also have this issue and as a-chaudhari mentions, this causes issues with currentUser in the rest of Nova. Whenever I navigate back it causes the a lot of things, such as the sidebar and other actions to disappear.

**Comment by simon-roland** [comment]
Same issue.

Click directly on the row in index view (Not on any link or button) causes 409 (Conflict) and a full page reload, which in turn causes problems with the currentUser prop.

Laravel 9.19.0, Laravel Nova 4.11.0, Nova Sortable 3.0.1

**Comment by stefblokdijk** [comment]
+1

On Safari I get a 404 error when pressing the back button after you've opened the detail page by clicking on the resource row. On Chrome I get multiple console log errors and the navigation disappears.

**Comment by KasparRosin** [comment]
Should be fixed via #132.
Released version 3.1.0
