### ISSUE TITLE
dragging rows often creates duplicate entries (visually)

### ISSUE THREAD

**Issue by a-chaudhari** [outl1ne/nova-sortable#134]
nova-sortable 4.1.0
nova 4.12.13
laravel 8.83.23
chrome 103.0.5060.134

There is an issue in nova-sortable in 4.x that wasn't present on 3.x.  When clicking and dragging around rows it'll often duplicate the row.  Thankfully this is only a visual bug as refreshing the page restores the correct count and expected positions.

Reproducing it isn't exact. But it's fairly straightforward if you click and drag rows to near the bottom of the list.  Doing it quickly appears it make it more likely.

In the below screenshot, I moved #7 down to between 9 and 10.  Seems like maybe the original entry wasn't removed from the local state which shows up as a duplicate value?

I disabled all other 3rd party nova packages to ensure no weird conflicts. 

![novasortabledups](https://user-images.githubusercontent.com/8324605/181571736-b245a516-19b1-44d7-8bd2-5bb98ab61ee7.PNG)

**Comment by rv-csanford** [comment]
I am also getting this issue!

**Comment by milewski** [comment]
Same issue

**Comment by kristher1619** [comment]
Same here

**Comment by zwok** [comment]
Hi, I have the same issue

**Comment by Tarpsvo** [comment]
Thanks for reporting this! Fixed in version 3.2.0. :)
