### ISSUE TITLE
Declaration of HasSortableRows::indexQuery() is incompatible with Nova's declaration

### ISSUE THREAD

**Issue by joschaefer** [outl1ne/nova-sortable#145]
- PHP: 8.1.10
- laravel: 9.34.0
- nova: 4.15.2
- nova-sortable: 3.2.1

Thank your for this great package! I wanted to let you know, that I receive the following error. Probably due to a changed method signature in Nova's `Resource::indexQuery()`:

```
Declaration of Outl1ne\NovaSortable\Traits\HasSortableRows::indexQuery(Laravel\Nova\Http\Requests\NovaRequest $request, $query) must be compatible with App\Nova\Resource::indexQuery(Laravel\Nova\Http\Requests\NovaRequest $request, $query): Illuminate\Database\Eloquent\Builder
```

I was able to temporarily fix it with the following code added to my Nova resource:

```php
use HasSortableRows {
    indexQuery as indexSortableQuery;
 }

public static function indexQuery(NovaRequest $request, $query): Builder
{
    // Prevents an error due to incompatible method signatures
    return parent::indexQuery($request, static::indexSortableQuery($request, $query));
}
```

**Comment by Tarpsvo** [comment]
I wonder if they undid that. In the version 1.71.1, it doesn't exist anymore:

![image](https://user-images.githubusercontent.com/2018660/198551115-4f9ccae4-825e-4243-8738-25f6cbe81ca9.png)

**Comment by Tarpsvo** [comment]
I checked version 4.15.2 as well and the PerformsQueries trait still doesn't include the return type of Builder. Are you sure this isn't your App\Nova\Resource which somehow overrides the indexQuery signature?
