### ISSUE TITLE
Nova v4.18.0

### ISSUE THREAD

**Issue by denniselsinga** [outl1ne/nova-sortable#148]
[**Nova will now disable the resource table row buttons instead of hiding them.**](https://nova.laravel.com/releases/4.18.0)

When using this package icons are still hidden. Is it possible to match the blade views from the new version?

**Comment by KasparRosin** [comment]
Seems the behaviour changed again in version 4.19.0

**Comment by denniselsinga** [comment]
Any news on this?

**Comment by saschaende** [comment]
Any news on that? How to fix it? Would like to use this but i can because no icons...

**Comment by KasparRosin** [comment]
Published version 3.4.0, that bumps laravel/nova version to latest (4.20.2).

**Comment by TonnyORG** [comment]
@KasparRosin thank you!
