### ISSUE TITLE
bug: nova-sortable + outl1ne/nova-translatable

### ISSUE THREAD

**Issue by IgorMeta** [outl1ne/nova-sortable#149]
Text::make('Name')->translatable(['en' => 'English', "pl" => 'Polski']);
After that, the Name field is returned back during sorting

**Comment by scramatte** [comment]
Same issue here. Please fix it

**Comment by KasparRosin** [comment]
Unable to reproduce with the latest 3.4.0 branch.
Maybe something changed that fixed this.

If this still reproduces for you, could you post more information or even better yet, create a repository where this issue reproduces.
