### ISSUE TITLE
Update 3.3.1 breaks light theme

### ISSUE THREAD

**Issue by proilyxa** [outl1ne/nova-sortable#157]
When we use light theme, table still has style from dark theme.

<img width="1666" alt="Снимок экрана 2023-01-12 в 14 55 10" src="https://user-images.githubusercontent.com/60401505/212085180-2a6d8f06-8e44-4ef5-8df8-4df1f0fb74bc.png">

**Comment by brain82** [comment]
It's worth mentioning that in dark mode, some colors are different.

![image](https://user-images.githubusercontent.com/6013683/212125970-60eb6c73-0061-47c3-9448-3e43688d6529.png)

**Comment by KasparRosin** [comment]
Seems laravel nova have configured gray to slate, which caused the tailwind configuration to show different colors.

**Comment by KasparRosin** [comment]
Thanks for the report.
Published version 3.4.1 that addresses these issues.
