### ISSUE TITLE
Scrolling sideways on resource index broken since nova 4.17.0

### ISSUE THREAD

**Issue by ramonfeleus** [outl1ne/nova-sortable#158]
- Laravel Version: 9.47.0
- Nova Version: >=4.17.0
- PHP Version: 8.1
- Browser type and version:  Google Chrome 108.0.5359.124 and others.

### Description:
Open a Nova Resource index page on a smaller screen where all columns do not fit horizontally in the viewport(e.g. smartphone, tablet, small desktop). Attempt to scroll sideways to view the other columns and action buttons. Scrolling sideways won't work.
This happened after we've upgraded a an older site's nova version to the latest 4.20.2 version.
After downgrading nova to specific versions I found that it has been an issue since nova 4.17.0. 
It seems the precedence of css classes on the list is the problem:
<img width="676" alt="Scherm­afbeelding 2023-01-13 om 15 51 18" src="https://user-images.githubusercontent.com/73035608/212351228-91fcbc89-71ec-491f-a03e-e25b04ca4c18.png">
The `o1-overflow-hidden` class sets an `overflow: hidden`, disallowing all scrolling on the overview. While `o1-overflow-x-auto` should enable scrolling on the horizontal x-axis by setting `overflow-x: auto`. But the `o1-overflow-hidden` overrides `o1-overflow-x-auto`. In the screenshot you will see that `o1-overflow-hidden` appears twice in the css inheritance in the inspector, indicating it might be in the css twice.

When I set composer to nova 4.16.1 it works. This has different html classes which make sure the scrolling on the x-axis is enabled again after setting `overflow: hidden` on the overview.

<img width="679" alt="Scherm­afbeelding 2023-01-13 om 15 52 35" src="https://user-images.githubusercontent.com/73035608/212352773-661ac26e-6ae3-4771-98f9-c6eb30472112.png">

The MenuBuilder.vue along with entry.css and entry.js from the nova-menu-builder are the only files within my project which actually have the `o1-overflow-hidden` class. So I'm guessing the menu builder is interfering with other resource index pages.

### Detailed steps to reproduce the issue:

- Upgrade to latests version or >= 4.17.0.
- Open index of resource with plenty of columns on a small screen, attempt to scroll horizontally to reveal other columns (no scrolling allowed).
- Downgrade nova to 4.16.1.
- Open index of resource with plenty of columns on a small screen, attempt to scroll horizontally to reveal other columns: scrolling works.

**Comment by KasparRosin** [comment]
@ramonfeleus Hey, thanks for the report.
I transfered the issue to nova-sortable, since I assume this package causes it.

Could you confirm, that you also have nova-sortable installed?

**Comment by ramonfeleus** [comment]
> @ramonfeleus Hey, thanks for the report. I transfered the issue to nova-sortable, since I assume this package causes it.
> 
> Could you confirm, that you also have nova-sortable installed?

Thanks. Yes, that's also in the stack, nova-translatable as well from Outl1ne.

**Comment by KasparRosin** [comment]
Published version 3.4.2 that addresses this issue.
Thanks for the report!
