### ISSUE TITLE
Sorting error | An error occurred while trying to reorder the resource

### ISSUE THREAD

**Issue by andreslora** [outl1ne/nova-sortable#159]
Hello,

I am getting these errors when I try to sort records:

Drag and drop 
 - An error occurred while trying to reorder the resource
 -  http://hiddendomain.io/nova-vendor/nova-sortable/sort/brands/update-order 404 (Not Found)

Sort button
 - http://hiddendomain.io/nova-vendor/nova-sortable/sort/brands/move-to-start 404 (Not Found)

Am I doing something wrong? I followed all the steps in the documentation.

Thank you in advance.

**Comment by KasparRosin** [comment]
My first idea is that, could you have cached your routes before you installed the package?
Quick `optimize:clear` or `route:clear` will prove the theory.

**Comment by andreslora** [comment]
Thank you, it worked. 

This is a really good package.

**Comment by KasparRosin** [comment]
Glad to hear it!
