### ISSUE TITLE
Incorrect table style when theme is set to "System"

### ISSUE THREAD

**Issue by brain82** [outl1ne/nova-sortable#160]
When I set the theme switcher to "System" and then refresh the page, tables look as shown in the screenshot.

I think the td tags (except the one with the checkboxes) are missing the dark:border-gray-700 class.

![image](https://user-images.githubusercontent.com/6013683/213081244-0760eb96-a848-4463-8932-eb2a24d90750.png)

**Comment by Tarpsvo** [comment]
Fixed in version 3.4.3. Thank you for reporting this!
