### ISSUE TITLE
Only dark mode available

### ISSUE THREAD

**Issue by gijsbeijer** [outl1ne/nova-sortable#163]
Hi,

It looks like dark mode is hardcoded into the plugin, is this correct?

I have my system settings to Dark, but when I select Light mode in Nova, the table stays in dark mode.

Regards Gijs

**Comment by marttinnotta** [comment]
> It looks like dark mode is hardcoded into the plugin, is this correct?

This is not correct. Dark mode is implemented same way Nova has done this and how Tailwind describes it in their docs. Moreover nova-settings itself does not create any components but reuses Nova's own components (only component we add is a message when you have no setting fields defined).

You can try clearing your browsers cache. Also make sure you have chosen "light" from modes not "system". Also note that each field or panel that you use has to have implemented dark mode.
