### ISSUE TITLE
shouldShowActionDropdown function missed on ResourceTableRow

### ISSUE THREAD

**Issue by armando-moreira** [outl1ne/nova-sortable#172]
Can this be added or is there any plan to do it in near future?
This allows showing/hiding inline actions.

**Comment by valentinrougier39** [comment]
Hi, It is possible to overload the Vue File to fix the problem in my project ?

**Comment by mstaack** [comment]
yeah this is needed to remove wrong/empty action-dropdown in index view

**Comment by mstaack** [comment]
@Tarpsvo do you mind having a look?

**Comment by CodeWithDennis** [comment]
**Running into the same problem when using this package:**

https://github.com/outl1ne/nova-sortable/assets/23448484/ae44c74d-ce35-43e5-83a1-e3da5b319685

**Comment by valentinrougier39** [comment]
> @Tarpsvo do you mind having a look?

In what way can I overload the vue File in my project please ?

**Comment by ndrez-outl1ne** [comment]
Please check if the [version 3.4.4](https://github.com/outl1ne/nova-sortable/releases/tag/3.4.4) fixes this issue.

**Comment by valentinrougier39** [comment]
Hi @ndrez-outl1ne , thank you it works ! 
I've the issue again only when nova is used on the tab (from nova-tabs), so I think I'll redirect the issue on nova-tabs package

**Comment by armando-moreira** [comment]
I can confirm it now work on version 3.4.4.
Thank you.
