### ISSUE TITLE
Disabled colors in dark mode incorrect

### ISSUE THREAD

**Issue by wimski** [outl1ne/nova-sortable#174]
I'm using 3.4.4 and in light mode the colors of the controls get more muted when they are disabled (as expected). In dark mode they get more prominent instead.

**Comment by ndrez-outl1ne** [comment]
The problem should be resolved in 3.4.5.

**Comment by wimski** [comment]
Any idea when 3.4.5 will be released?

**Comment by ndrez-outl1ne** [comment]
Check the [pre-release](https://github.com/outl1ne/nova-sortable/releases/tag/3.4.5) and see if it works as expected. If no other style issues are found, it will be set as the latest version.

**Comment by wimski** [comment]
Yes, the pre-release fixes my issue.
